version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - DATABASE_URL=sqlite:///./doganai.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - API_KEY=dev-api-key
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:80
    volumes:
      - ./src:/app/src
      - ./backend:/app/backend
      - ./app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - doganai-dev

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_ENV=development
    networks:
      - doganai-dev

  # Database (SQLite for development, can switch to PostgreSQL)
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=doganai
      - POSTGRES_PASSWORD=doganai
      - POSTGRES_DB=doganai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - doganai-dev

networks:
  doganai-dev:
    driver: bridge

volumes:
  postgres_dev_data:
