version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=http://localhost:3001
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    ports:
      - "8010:8000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8010
    ports:
      - "3001:3001"
    depends_on:
      - api
