regulator: "SAMA"
version: "1.0.0"
title: "Saudi Central Bank Regulatory Framework"
description: "Saudi Arabia's Central Bank compliance framework for financial institutions and banking services"
authority: "Saudi Central Bank (SAMA)"
jurisdiction: "Saudi Arabia"
effective_date: "2024-01-01"
last_updated: "2024-08-29"
controls:
  - id: "SAMA-01"
    title_ar: "نهج انعدام الثقة"
    title_en: "Zero Trust"
    requirement_ar: "تطبيق سياسة Zero Trust على الشبكات والمستخدمين."
    requirement_en: "Apply Zero Trust across networks and identities."
    category: "Access Control"
    severity: "High"
    
api_config:
  base_url: "https://api.sama.gov.sa/v1"
  endpoints:
    compliance_check: "/compliance/banking"
    transaction_monitoring: "/monitoring/transactions"
    risk_reporting: "/reports/risk"
    audit_trail: "/audit/trail"
  rate_limit: 200
  timeout: 60

authentication:
  type: "oauth2"
  token_url: "https://auth.sama.gov.sa/oauth/token"
  scopes: ["banking:read", "compliance:write", "audit:read"]
  client_credentials: true
  encryption: "RSA-2048"

reporting:
  frequency: "monthly"
  format: ["json", "xml", "encrypted"]
  endpoints:
    submit: "/reports/banking/submit"
    status: "/reports/banking/status"
  required_fields:
    - "zero_trust_implementation_status"
    - "access_control_metrics"
    - "transaction_security_reports"
    - "risk_management_indicators"
    - "compliance_audit_results"

penalties:
  - violation: "Inadequate access controls"
    fine_range: "2,000,000 - 20,000,000 SAR"
    enforcement: "Banking license review possible"
  - violation: "Zero trust non-compliance"
    fine_range: "1,000,000 - 10,000,000 SAR"
    enforcement: "Security enhancement plan required"

contact:
  name: "Saudi Central Bank (SAMA)"
  website: "https://www.sama.gov.sa"
  email: "compliance@sama.gov.sa"
  phone: "+966-11-4633000"
