{{- if and .Values.security.networkPolicies.enabled .Values.security.networkPolicies.defaultDenyEgress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "doganai.fullname" . }}-default-deny-egress
  labels:
    {{- include "doganai.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
{{- end }}
