{{- if .Values.security.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "doganai.fullname" . }}-allow-monitoring
  labels:
    {{- include "doganai.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.security.networkPolicies.monitoringNamespace | default "doganai-monitoring" | quote }}
      ports:
        - protocol: TCP
          port: 9100
        - protocol: TCP
          port: 8001
{{- end }}
