apiVersion: v1
kind: Service
metadata:
  name: {{ include "doganai.fullname" . }}-app
  labels:
    {{- include "doganai.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP
