apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: doganai-fast-ssd
provisioner: kubernetes.io/aws-ebs  # Change based on your cloud provider
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: doganai-gpu-storage
provisioner: kubernetes.io/aws-ebs  # Change based on your cloud provider
parameters:
  type: io2
  iops: "16000"
  throughput: "1000"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-pvc
  namespace: doganai-compliance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-pvc
  namespace: doganai-compliance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-pvc
  namespace: doganai-compliance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: doganai-compliance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: doganai-logging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: doganai-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: doganai-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: doganai-fast-ssd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-models-pvc
  namespace: doganai-compliance
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: doganai-gpu-storage
  resources:
    requests:
      storage: 1Ti
