---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-server-sa
  namespace: doganai-compliance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-server-role
  namespace: doganai-compliance
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-server-rb
  namespace: doganai-compliance
subjects:
  - kind: ServiceAccount
    name: app-server-sa
roleRef:
  kind: Role
  name: app-server-role
  apiGroup: rbac.authorization.k8s.io
