---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: doganai-standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
