name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint (ruff)
        run: ruff .
      - name: Format check (black)
        run: black --check .
      - name: Import order check (isort)
        run: isort --check-only .
      - name: Type check (mypy)
        run: mypy .
      - name: Security scan (bandit)
        run: bandit -q -r engine || true
      - name: Tests
        run: pytest -q
