name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'mypy.ini'
      - '.flake8'
      - 'requirements*.txt'
  pull_request:
    branches: [ '**' ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'mypy.ini'
      - '.flake8'
      - 'requirements*.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Lint (flake8)
        run: flake8 .

      - name: Format check (black)
        run: black --check .

      - name: Imports check (isort)
        run: isort --profile black --check-only .

      - name: Type check (mypy)
        run: mypy --ignore-missing-imports src

      - name: Security scan (bandit)
        run: bandit -r src -x src/tests

      - name: Run tests
        run: pytest -q
