name: CI/CD
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  APP: doganai-compliance-kit

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/doganai-compliance-kit:${{ github.sha }},${{ secrets.DOCKER_REGISTRY }}/doganai-compliance-kit:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure kubectl (optional)
        if: ${{ secrets.KUBECONFIG != '' }}
        run: |
          echo "$KUBECONFIG_B64" | base64 -d > $HOME/.kube/config
          kubectl config set-context --current --namespace=${{ vars.K8S_NAMESPACE || 'prod' }}
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}

      - name: Deploy (kubectl)
        if: ${{ secrets.KUBECONFIG != '' }}
        run: |
          IMAGE=${{ secrets.DOCKER_REGISTRY }}/doganai-compliance-kit:${{ github.sha }}
          sed "s#{{IMAGE}}#$$IMAGE#g" k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl rollout status deploy/doganai-compliance-kit -n ${{ vars.K8S_NAMESPACE || 'prod' }}
