name: Lighthouse CI

on:
  pull_request:
    branches: [ '**' ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
      - 'Dockerfile.web'
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
      - 'Dockerfile.web'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: corepack prepare pnpm@9 --activate
      - name: Install deps (workspace)
        run: pnpm -w install
      - name: Build tokens
        run: pnpm -w run tokens:build
      - name: Build web
        run: pnpm --filter @apps/web build
      - name: Start web
        run: pnpm --filter @apps/web start -p 3001 &
      - name: Wait for web
        run: |
          for i in {1..30}; do curl -fsS http://localhost:3001 && break || sleep 2; done
      - name: Run Lighthouse CI (with budgets/assertions)
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: '.lighthouserc.json'
          uploadArtifacts: true
