name: Security Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  python-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit
      - name: Run pip-audit
        run: pip-audit -r requirements-api.txt || true

  frontend-audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install
        run: npm install --no-audit --no-fund
      - name: npm audit (non-blocking)
        run: npm audit --omit=dev || true

